# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_settings <- function(solver_p, dense_backend) {
    .Call('_piqp_get_settings', PACKAGE = 'piqp', solver_p, dense_backend)
}

update_settings <- function(solver_p, dense_backend, settings) {
    invisible(.Call('_piqp_update_settings', PACKAGE = 'piqp', solver_p, dense_backend, settings))
}

piqp_dense_setup <- function(P, c, A, b, G, h, x_lb, x_ub, settings) {
    .Call('_piqp_piqp_dense_setup', PACKAGE = 'piqp', P, c, A, b, G, h, x_lb, x_ub, settings)
}

piqp_sparse_setup <- function(P, c, A, b, G, h, x_lb, x_ub, settings) {
    .Call('_piqp_piqp_sparse_setup', PACKAGE = 'piqp', P, c, A, b, G, h, x_lb, x_ub, settings)
}

solve_model <- function(solver_p, dense_backend) {
    .Call('_piqp_solve_model', PACKAGE = 'piqp', solver_p, dense_backend)
}

piqp_update_dense <- function(solver_p, P, c, A, b, G, h, x_lb, x_ub) {
    invisible(.Call('_piqp_piqp_update_dense', PACKAGE = 'piqp', solver_p, P, c, A, b, G, h, x_lb, x_ub))
}

piqp_update_sparse <- function(solver_p, P, c, A, b, G, h, x_lb, x_ub) {
    invisible(.Call('_piqp_piqp_update_sparse', PACKAGE = 'piqp', solver_p, P, c, A, b, G, h, x_lb, x_ub))
}

